[package]
name = "framewase-project-manager"
version = "0.0.1"
edition= "2024"

[profile.release]
strip = true
opt-level = "z"
lto = true
codegen-units = 1

[[bin]]
name = "project-manager"
path = "../project_manager/src/rust/main.c

[build]
jobs = 8
target-dir = "../build/"

